#! /bin/sh
# Simple script that changes figure paths. From figs_bmp
# (low-quality png encoded eps figures for arxiv submission) 
# to figs (high quality for journal submission).

find . -type f -name "*.tex" -print | while read i
do
	sed "s|figs_bmp/|figs/|g" $i > $i.tmp && mv $i.tmp $i
done

