#! /bin/sh
# Simple script that changes figure paths. From figs (high-quality)
# to figs_bmp (low-quality png encoded eps figures for arxiv submission.)

find . -type f -name "*.tex" -print | while read i
do
	sed "s|figs/|figs_bmp/|g" $i > $i.tmp && mv $i.tmp $i
done

