#!/bin/bash
# $Author: siminos $ $Date: 2008-01-02 01:10:19 -0500 (Wed, 02 Jan 2008) $

	latex DDays08.tex
	bibtex DDays08 
	latex DDays08.tex
	latex DDays08.tex
	dvips -o DDays08.ps DDays08.dvi
	ps2pdf DDays08.ps

