#!/bin/bash
# $Author: siminos $ $Date: 2008-01-01 18:54:45 -0500 (Tue, 01 Jan 2008) $

	latex GTretreat07.tex
	bibtex GTretreat07 
	latex GTretreat07.tex
	latex GTretreat07.tex
	dvips -o GTretreat07.ps text.dvi

